-- ============================================================================
-- Migration 021: Re-key favorites from participant to pick_set
--
-- The original favorites feature (migration 020) modelled a favorite as
-- an edge between two participants: a logged-in user followed another
-- participant in the pool, and ALL of that participant's pick sets
-- showed up on the Favorites tab. Product spec was revised: favoriting
-- should be per-pick-set, so a user can favorite "Heather Collins 1"
-- independently of "Heather Collins 2" and "Heather Collins 3".
--
-- This migration:
--   1. Drops the old favorite_participant_id column (and its unique
--      constraint and indexes).
--   2. Adds favorite_pick_set_id, pointing at pick_sets(id) with cascade
--      delete (so deleting a pick set removes any favorites of it).
--   3. Adds a UNIQUE(pool_id, participant_id, favorite_pick_set_id)
--      constraint so the same user can't favorite the same pick set
--      twice.
--   4. Adds the same two index shapes the old design had, just keyed on
--      pick set instead of participant.
--
-- DATA LOSS
-- ---------
-- This migration intentionally DROPS existing favorite rows rather than
-- attempting to expand each old (favoriter → participant) edge into
-- (favoriter → all of that participant's pick sets). Reasons:
--   - The only existing favorite data is the demo seed (Heather's
--     favorites), which is regenerated by seed-demo.ts on every run.
--   - Real users have not yet started using the feature.
--   - An automated expansion would be lossy in the other direction:
--     once expanded, a user who only ever wanted Heather Collins 1
--     would be stuck with rows for 2 and 3 too. Forcing them to
--     re-favorite from scratch is the safer default.
--
-- If real production data ever needs to be preserved through a similar
-- re-keying, do the migration in two steps: (a) add the new column,
-- (b) backfill via a DO block, (c) drop the old column.
--
-- IDEMPOTENCY
-- -----------
-- All statements use IF EXISTS / IF NOT EXISTS guards or are wrapped in
-- DO blocks that probe pg_catalog first. Safe to re-run.
-- ============================================================================

-- 1. Drop existing rows. The whole reason for the drop is explained
--    above — we're not preserving them across the re-keying.
DELETE FROM pool_favorites;

-- 2. Drop the old unique constraint by its implicit name. Postgres
--    auto-names the constraint from migration 020's UNIQUE(...) clause
--    as `pool_favorites_pool_id_participant_id_favorite_participant_id_key`.
--    We probe pg_constraint defensively in case the name was set
--    differently in a partially-applied environment.
DO $$
DECLARE
    constraint_name TEXT;
BEGIN
    SELECT conname INTO constraint_name
    FROM pg_constraint
    WHERE conrelid = 'pool_favorites'::regclass
      AND contype = 'u'
      AND pg_get_constraintdef(oid) LIKE '%favorite_participant_id%';

    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE pool_favorites DROP CONSTRAINT %I',
                       constraint_name);
    END IF;
END $$;

-- 3. Drop the two indexes from migration 020. Both are explicitly named
--    so IF EXISTS keeps this idempotent.
DROP INDEX IF EXISTS idx_pool_favorites_pool_participant;
DROP INDEX IF EXISTS idx_pool_favorites_favorite;

-- 4. Drop the old column. The FK on participants(id) goes with it.
ALTER TABLE pool_favorites
    DROP COLUMN IF EXISTS favorite_participant_id;

-- 5. Add the new column. NOT NULL is enforced at add time; safe
--    because we wiped the table in step 1.
ALTER TABLE pool_favorites
    ADD COLUMN IF NOT EXISTS favorite_pick_set_id UUID NOT NULL
    REFERENCES pick_sets(id) ON DELETE CASCADE;

-- 6. New unique constraint — wrapped in a DO block so re-running
--    against an environment where it already exists is a no-op.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'pool_favorites_pool_participant_pickset_key'
          AND conrelid = 'pool_favorites'::regclass
    ) THEN
        ALTER TABLE pool_favorites
            ADD CONSTRAINT pool_favorites_pool_participant_pickset_key
            UNIQUE(pool_id, participant_id, favorite_pick_set_id);
    END IF;
END $$;

-- 7. Hot lookup path — "favorites for THIS user in THIS pool", same
--    shape as the old idx_pool_favorites_pool_participant. The leading
--    (pool_id, participant_id) prefix still serves the per-user
--    query; the unique constraint above provides the
--    (pool_id, participant_id, favorite_pick_set_id) shape for
--    duplicate checks on insert.
CREATE INDEX IF NOT EXISTS idx_pool_favorites_pool_participant
    ON pool_favorites(pool_id, participant_id);

-- 8. Reverse lookup, unused for now but cheap — "who's favoriting this
--    pick set?". Useful for future surface area (follower counts on a
--    player's profile).
CREATE INDEX IF NOT EXISTS idx_pool_favorites_pickset
    ON pool_favorites(favorite_pick_set_id);
